# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WDTrendsModuleKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WDTrendsModuleKit

  target 'WDTrendsModuleKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WDTrendsModuleKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end


pod 'Masonry', '1.0.2'

end
